name: Docker Build & Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Run container (for test)
        run: |
          docker run -d -p 5000:5000 --name test-container my-python-app
          sleep 5

      - name: Check container logs
        run: |
          docker logs test-container

      - name: Stop containe
        run: |
          docker stop test-container
          docker rm test-container
